### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [juancinfante/Backend_ProyectoFinal_RC#4]
Buenas! encontre algunos console.log que no deberian estar..
![image](https://github.com/juancinfante/Backend_ProyectoFinal_RC/assets/53904695/90667f51-54ba-4945-92ee-ae1d8667da00)
los console.log en los catch o en donde necesitemos mostrar un error a los usuario por consola, deberian ser console.error

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juancinfante** [comment]
Buenas, ya los corregí.
