### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [juancinfante/Backend_ProyectoFinal_RC#5]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/juancinfante/Backend_ProyectoFinal_RC/assets/53904695/7335a076-d6b3-4269-9be3-2eea64dea1dd)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juancinfante** [comment]
Comentarios borrados.

**Comment by juancinfante** [comment]
Hola nico, ya se solucionaron los issues, tanto en el front como en el back,
Back : juancinfante/Backend_ProyectoFinal_RC (github.com)
<https://github.com/juancinfante/Backend_ProyectoFinal_RC>
Front : juedsay/ProyectoFinal_RC: Proyecto Final del Bootcamp de
Desarrollador Full-Stack - RollingCode Academy (github.com)
<https://github.com/juedsay/ProyectoFinal_RC>
Deploy : Delivery Fast (fastlibery.netlify.app)
<https://fastlibery.netlify.app/>

PD: Agradecería si me respondes a este mail solamente, ya sea por issues
del back o front.

**Comment by Nidev-lab** [comment]
Buenas! Estuve revisando las modificaciones y esta todo Ok, eso seria todo. Felicidades!

**Comment by juancinfante** [comment]
Muchas gracias! Como continuo ahora, solo debo esperar?
